In [5]:
import tensorflow as tf
import numpy as np
import os 
os.environ["TF_CPP_MIN_LEVEL"]="3"

In [6]:
AMatrix = np.array([(1.0,1.0,1.0), (1.0,1.0,1.0),(1.0,1.0,1.0)],dtype=float)
BMatrix = np.array([(3.0,3.0,3.0), (3.0,3.0,3.0),(3.0,3.0,3.0)],dtype=float)

In [7]:
ATMatrix=tf.constant(AMatrix)
BTMatrix=tf.constant(BMatrix)

In [9]:
SumMatrix=tf.add(ATMatrix, BTMatrix)
ProductMatrix=tf.matmul(ATMatrix, BTMatrix)
DetMatrix=tf.matrix_determinant(AMatrix)

In [10]:
print(SumMatrix)
print(ProductMatrix)

Tensor("Add_1:0", shape=(3, 3), dtype=float64)
Tensor("MatMul_1:0", shape=(3, 3), dtype=float64)


In [11]:
with tf.Session() as sess:
        AResult = sess.run(SumMatrix)
        BResult = sess.run(ProductMatrix)
        CResult = sess.run(DetMatrix)

In [13]:
print(AResult)

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [16]:
print(BResult)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [17]:
print(CResult)

0.0
